name: schema-registry-yang-format
lang: java
lang_version: 17
git:
  enable: true
github:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  nano_version: true
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/io.confluent/schema-registry-extensions
    - maven-snapshots/maven/io.confluent/kafka-yang-schema-provider
    - maven-snapshots/maven/io.confluent/yang-schema
